import { test } from "node:test";
import { equal } from "assert";
import { toolImplementations } from "./tools.js";

test("should run javascript tool", async () => {
  const result = await toolImplementations.run_javascript({
    script: `
    return "hello";    
  `,
  });
  equal(result, JSON.stringify("hello"));
});

test("should run script generated by model", async () => {
  const script = `function fibonacciUpTo(max) {
    let sequence = [0, 1];
    while (true) {
        let nextValue = sequence[sequence.length - 1] + sequence[sequence.length - 2];
        if (nextValue > max) break;
        sequence.push(nextValue);
    }
    return sequence;
}

let result = fibonacciUpTo(50);
return result;`;
  const result = await toolImplementations.run_javascript({ script });
  equal(result, JSON.stringify([0, 1, 1, 2, 3, 5, 8, 13, 21, 34]));
});
