name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  rununittest:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: |
          curl https://wasmtime.dev/install.sh -sSf | bash
          export PATH="$HOME/.wasmtime/bin:$PATH"
          rustup target add wasm32-wasi
          cargo install cargo-wasi
          ./test.sh
          (cd testenv && ./test.sh)
          (cd examples/nft && ./test.sh)
          (cd examples/minimumweb4 && ./test.sh)
  e2etests:
    name: End to end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: End to end tests
        run: |
          set -e
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_111/binaryen-version_111-x86_64-linux.tar.gz | tar xzf -
          export PATH="`pwd`/binaryen-version_111/bin:$PATH"
          npm install -g near-cli
          rustup target add wasm32-unknown-unknown
          mkdir out
          ./buildanddeploy.sh
          yarn install
          yarn test-e2e
  e2e-test-example-nft:
    name: NFT example End to End tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NFT example End to End tests
        run: |
          set -e
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_111/binaryen-version_111-x86_64-linux.tar.gz | tar xzf -
          export PATH="`pwd`/binaryen-version_111/bin:$PATH"
          npm install -g near-cli
          mkdir $HOME/.near-config
          echo "{\"trackingEnabled\": true, \"trackingAccountID\": false}" > $HOME/.near-config/settings.json
          rustup target add wasm32-unknown-unknown
          yarn install
          cd examples/nft
          mkdir out
          ./buildanddeploy.sh          
          yarn test-examples-nft-e2e
  localjs-test-example-nft:
    name: NFT example local JS test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NFT example End to End tests
        run: |
          set -e
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_111/binaryen-version_111-x86_64-linux.tar.gz | tar xzf -
          export PATH="`pwd`/binaryen-version_111/bin:$PATH"
          rustup target add wasm32-unknown-unknown
          yarn install
          cd examples/nft
          mkdir out
          yarn test-examples-nft-localjs
  webapptests:
    name: Web app tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Web app tests
        run: |
          yarn install
          yarn test-web
