name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  rununittest:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: |
          curl https://wasmtime.dev/install.sh -sSf | bash
          rustup target add wasm32-wasi
          ./test.sh
  e2etests:
    name: End to end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: End to end tests
        run: |
          npm install -g near-cli
          rustup target add wasm32-unknown-unknown
          mkdir out
          ./buildanddeploy.sh
          yarn install
          yarn e2e
