name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  rununittest:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: |
          ./.devcontainer/install-dependencies.sh
          ./test.sh
          (cd testenv && ./test.sh)
          (cd examples/nft && ./test.sh)
          (cd examples/minimumweb4 && ./test.sh)
          (cd examples/fungibletoken && ./test.sh)
  e2etests:
    name: End to end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: End to end tests
        run: |
          set -e
          ./.devcontainer/install-dependencies.sh
          npm install -g near-cli
          mkdir out
          ./build.sh
          yarn install
          yarn test-e2e
  e2e-test-example-nft:
    name: NFT example End to End tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: NFT example End to End tests
        run: |
          set -e
          ./.devcontainer/install-dependencies.sh
          yarn install
          cd examples/nft
          mkdir out
          ./build.sh          
          yarn test-examples-nft-e2e
  localjs-test-example-nft:
    name: NFT example local JS test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: NFT example local JS test
        run: |
          set -e
          ./.devcontainer/install-dependencies.sh
          yarn install
          cd examples/nft
          mkdir out
          yarn test-examples-nft-localjs
  localjs-test-example-purejs:
    name: PureJS example local JS test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: PureJS example local JS test
        run: |
          set -e
          ./.devcontainer/install-dependencies.sh
          yarn install
          yarn test-purejs
  webapptests:
    name: Web app tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Web app tests
        run: |
          yarn install
          yarn test-web
