name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  rununittest:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: |
          wget https://github.com/WebAssembly/wabt/releases/download/1.0.35/wabt-1.0.35.tar.xz
          tar -xvf wabt-1.0.35.tar.xz
          cd wabt-1.0.35
          mkdir build
          cd build
          cmake ..
          sudo cmake --build . --target install
          cd ..
          cd ..

          curl https://wasmtime.dev/install.sh -sSf | bash
          wget https://bellard.org/quickjs/quickjs-2024-01-13.tar.xz
          tar -xf quickjs-2024-01-13.tar.xz
          rm quickjs-2024-01-13.tar.xz

          export PATH="$HOME/.wasmtime/bin:$PATH"
          rustup target add wasm32-wasi
          rustup target add wasm32-wasip1
          cargo install cargo-wasi
          ./test.sh
          (cd testenv && ./test.sh)
          (cd examples/nft && ./test.sh)
          (cd examples/minimumweb4 && ./test.sh)
          (cd examples/fungibletoken && ./test.sh)
  e2etests:
    name: End to end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: End to end tests
        run: |
          set -e
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_111/binaryen-version_111-x86_64-linux.tar.gz | tar xzf -
          export PATH="`pwd`/binaryen-version_111/bin:$PATH"
          npm install -g near-cli
          rustup target add wasm32-unknown-unknown
          mkdir out
          ./build.sh
          yarn install
          yarn test-e2e
  e2e-test-example-nft:
    name: NFT example End to End tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: NFT example End to End tests
        run: |
          set -e
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_111/binaryen-version_111-x86_64-linux.tar.gz | tar xzf -
          export PATH="`pwd`/binaryen-version_111/bin:$PATH"
          rustup target add wasm32-unknown-unknown
          yarn install
          cd examples/nft
          mkdir out
          ./build.sh          
          yarn test-examples-nft-e2e
  localjs-test-example-nft:
    name: NFT example local JS test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: NFT example local JS test
        run: |
          set -e
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_111/binaryen-version_111-x86_64-linux.tar.gz | tar xzf -
          export PATH="`pwd`/binaryen-version_111/bin:$PATH"
          rustup target add wasm32-unknown-unknown
          yarn install
          cd examples/nft
          mkdir out
          yarn test-examples-nft-localjs
  localjs-test-example-purejs:
    name: PureJS example local JS test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: PureJS example local JS test
        run: |
          set -e
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_111/binaryen-version_111-x86_64-linux.tar.gz | tar xzf -
          export PATH="`pwd`/binaryen-version_111/bin:$PATH"
          curl -L https://github.com/WebAssembly/wabt/releases/download/1.0.33/wabt-1.0.33-ubuntu.tar.gz | tar xzf -
          export PATH="`pwd`/wabt-1.0.33/bin:$PATH"
          rustup target add wasm32-unknown-unknown
          yarn install
          yarn test-purejs
  webapptests:
    name: Web app tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Web app tests
        run: |
          yarn install
          yarn test-web
