name: Release example contracts

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]
      
jobs:
  buildexamplecontracts:
    name: Build example contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.wasmtime
            ~/.cargo
            bin
            node_modules
            emsdk
            wabt-1.0.35
            binaryen-version_116
            quickjs-2024-01-13
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/yarn.lock', '.devcontainer/install-dependencies.sh') }}

      - name: Set up paths and Rust
        run: |
          echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH
          echo "$(pwd)/binaryen-version_116/bin" >> $GITHUB_PATH
          echo "$(pwd)/wabt-1.0.35/bin" >> $GITHUB_PATH
          rustup target add wasm32-wasip1 
          rustup target add wasm32-unknown-unknown

      - name: Build example contracts
        run: |
          (cd examples/nft && ./build.sh)
          (cd examples/minimumweb4 && ./build.sh)
          (cd examples/fungibletoken && ./build.sh)
    
      - name: Package WASM files into a ZIP
        run: |
          mkdir -p release
          zip -j release/example_contracts.zip examples/nft/out/nft.wasm examples/minimumweb4/out/minimum_web4.wasm examples/fungibletoken/out/fungible_token.wasm

      - name: Upload WASM ZIP artifact
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: wasm-zip
          path: release/example_contracts.zip
  
  release:
    name: Create Release
    needs: buildexamplecontracts
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download WASM ZIP artifact
        uses: actions/download-artifact@v4
        with:
          name: wasm-zip

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload ZIP file to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./example_contracts.zip
          asset_name: example_contracts.zip
          asset_content_type: application/zip
