name: "AI proxy tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: "AI proxy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash
          sudo mv spin /usr/local/bin/
          rustup target add wasm32-wasi
          cargo install cargo-component --locked
          spin plugin install -y -u https://github.com/fermyon/spin-test/releases/download/canary/spin-test.json
      - name: Check formatting
        working-directory: examples/aiproxy
        run: |
          (cd openai-proxy && cargo fmt --check)
          (cd tests && cargo fmt --check)
      - name: Build project
        working-directory: examples/aiproxy
        run: |
          spin build
      - name: Run tests
        working-directory: examples/aiproxy
        run: |
          spin test
